/**
 * 浏览器模式下优先走 mock 的命令集合。
 *
 * 这些命令要么依赖当前 DevBridge 尚未桥接的原生能力，
 * 要么即使缺少真实后端也不应阻塞默认页面渲染。
 */

const mockPriorityCommands = new Set<string>([
  "agent_runtime_export_analysis_handoff",
  "agent_runtime_export_handoff_bundle",
  "agent_runtime_export_evidence_pack",
  "agent_runtime_export_review_decision_template",
  "agent_runtime_save_review_decision",
  "agent_runtime_export_replay_case",
  "companion_get_pet_status",
  "companion_launch_pet",
  "companion_send_pet_command",
  "list_dir",
  "get_file_icon_data_url",
  "get_file_manager_locations",
  "get_plugin_status",
  "get_plugins",
  "list_installed_plugins",
  "list_plugin_tasks",
  "get_plugin_queue_stats",
  "subscribe_sysinfo",
  "unsubscribe_sysinfo",
  "session_files_get_or_create",
  "session_files_update_meta",
  "session_files_list_files",
  "session_files_read_file",
  "session_files_delete_file",
  "save_exported_document",
  "save_layered_design_project_export",
  "read_layered_design_project_export",
  "execution_run_get_general_workbench_state",
  "get_hint_routes",
  "memory_runtime_get_working_memory",
  "memory_runtime_get_extraction_status",
  "memory_runtime_prefetch_for_turn",
  "memory_cleanup_memdir",
  "memory_scaffold_memdir",
  "openclaw_check_installed",
  "openclaw_get_environment_status",
  "openclaw_check_node_version",
  "openclaw_check_git_available",
  "openclaw_get_node_download_url",
  "openclaw_get_git_download_url",
  "openclaw_install",
  "openclaw_install_dependency",
  "openclaw_get_command_preview",
  "openclaw_uninstall",
  "openclaw_cleanup_temp_artifacts",
  "openclaw_start_gateway",
  "openclaw_stop_gateway",
  "openclaw_restart_gateway",
  "openclaw_get_status",
  "openclaw_check_health",
  "openclaw_get_dashboard_url",
  "openclaw_get_channels",
  "openclaw_get_progress_logs",
  "openclaw_sync_provider_config",
  "close_webview_panel",
  "get_webview_panels",
  "focus_webview_panel",
  "navigate_webview_panel",
  "get_browser_connector_settings_cmd",
  "set_browser_connector_install_root_cmd",
  "set_browser_connector_enabled_cmd",
  "set_system_connector_enabled_cmd",
  "set_browser_action_capability_enabled_cmd",
  "get_browser_connector_install_status_cmd",
  "install_browser_connector_extension_cmd",
  "open_browser_extensions_page_cmd",
  "open_browser_remote_debugging_page_cmd",
  "open_browser_connector_guide_window",
  "disconnect_browser_connector_session",
  "launch_browser_session",
  "launch_browser_profile_runtime_assist_cmd",
  "get_browser_action_audit_logs",
]);

/**
 * 浏览器模式下必须以桥接后端为真相源的命令集合。
 *
 * 这些命令一旦桥接失败，就必须直接暴露错误；
 * 不能再静默回退到 mock，把“后端未连上 / 命令失败”伪装成“只是没有数据”。
 */
const bridgeTruthCommands = new Set<string>([
  "aster_agent_init",
  "aster_agent_status",
  "agent_generate_title",
  "get_or_create_default_project",
  "workspace_list",
  "workspace_get_default",
  "workspace_get",
  "workspace_ensure_ready",
  "agent_runtime_submit_turn",
  "agent_runtime_interrupt_turn",
  "agent_runtime_compact_session",
  "agent_runtime_resume_thread",
  "agent_runtime_replay_request",
  "agent_runtime_get_thread_read",
  "agent_runtime_list_file_checkpoints",
  "agent_runtime_get_file_checkpoint",
  "agent_runtime_diff_file_checkpoint",
  "agent_runtime_promote_queued_turn",
  "agent_runtime_remove_queued_turn",
  "agent_runtime_respond_action",
  "agent_runtime_create_session",
  "agent_runtime_list_sessions",
  "agent_runtime_get_session",
  "agent_runtime_update_session",
  "agent_runtime_delete_session",
  "agent_runtime_get_tool_inventory",
  "agent_runtime_spawn_subagent",
  "agent_runtime_send_subagent_input",
  "agent_runtime_wait_subagents",
  "agent_runtime_resume_subagent",
  "agent_runtime_close_subagent",
  "sceneapp_list_catalog",
  "sceneapp_get_descriptor",
  "sceneapp_plan_launch",
  "sceneapp_save_context_baseline",
  "sceneapp_create_automation_job",
  "sceneapp_list_runs",
  "sceneapp_get_run_summary",
  "sceneapp_prepare_run_governance_artifact",
  "sceneapp_get_scorecard",
  "gateway_channel_status",
  "wechat_channel_list_accounts",
  "get_default_provider",
  "get_provider_ui_state",
  "get_api_key_providers",
  "get_api_key_provider",
  "add_custom_api_key_provider",
  "update_api_key_provider",
  "delete_custom_api_key_provider",
  "add_api_key",
  "get_model_registry",
  "get_model_registry_provider_ids",
  "get_models_for_provider",
  "get_models_by_tier",
  "get_provider_alias_config",
  "get_all_alias_configs",
  "refresh_model_registry",
  "fetch_provider_models_auto",
  "create_image_generation_task_artifact",
  "create_audio_generation_task_artifact",
  "complete_audio_generation_task_artifact",
  "get_media_task_artifact",
  "list_media_task_artifacts",
  "cancel_media_task_artifact",
  "capability_draft_create",
  "capability_draft_list",
  "capability_draft_get",
  "capability_draft_verify",
  "capability_draft_register",
  "capability_draft_list_registered_skills",
  "capability_draft_submit_approval_session_inputs",
  "capability_draft_execute_controlled_get",
  "agent_runtime_list_workspace_skill_bindings",
  "knowledge_import_source",
  "knowledge_compile_pack",
  "knowledge_list_packs",
  "knowledge_get_pack",
  "knowledge_set_default_pack",
  "knowledge_update_pack_status",
  "knowledge_resolve_context",
  "knowledge_validate_context_run",
  "session_files_save_file",
  "read_file_preview_cmd",
  "session_files_resolve_file_path",
  "upload_material",
  "voice_models_download",
  "voice_models_delete",
  "voice_models_set_default",
  "voice_models_test_transcribe_file",
]);

const bridgeTruthEventPrefixes = [
  "voice-model-download-progress",
  "aster_stream_",
  "agent_subagent_status:",
  "agent_subagent_stream:",
];

export function shouldPreferMockInBrowser(cmd: string): boolean {
  return mockPriorityCommands.has(cmd);
}

export function shouldDisallowMockFallbackInBrowser(cmd: string): boolean {
  return bridgeTruthCommands.has(cmd);
}

export function shouldDisallowMockEventFallbackInBrowser(
  eventName: string,
): boolean {
  const normalizedEventName = eventName.trim();
  if (!normalizedEventName) {
    return false;
  }
  return bridgeTruthEventPrefixes.some((prefix) =>
    normalizedEventName.startsWith(prefix),
  );
}
