- generic [ref=e2]:
  - generic [ref=e14]:
    - complementary [ref=e15]:
      - generic [ref=e16]:
        - generic [ref=e17]:
          - button "Lime Lime" [ref=e18] [cursor=pointer]
          - button "折叠导航栏" [ref=e22] [cursor=pointer]
        - button "搜索任务" [ref=e26] [cursor=pointer]:
          - img [ref=e27]
          - generic [ref=e30]: 搜索任务
      - generic [ref=e31]:
        - generic [ref=e32]:
          - generic [ref=e33]: 任务
          - button "新建任务" [ref=e34] [cursor=pointer]
          - button "生成" [ref=e37] [cursor=pointer]
        - generic [ref=e41]:
          - generic [ref=e42]: 能力
          - button "我的方法" [ref=e43] [cursor=pointer]
          - button "创作场景" [ref=e47] [cursor=pointer]
          - button "持续流程" [active] [ref=e53] [cursor=pointer]
          - button "消息渠道" [ref=e57] [cursor=pointer]
        - generic [ref=e62]:
          - generic [ref=e63]: 资料
          - button "资料库" [ref=e64] [cursor=pointer]
          - button "灵感库" [ref=e68] [cursor=pointer]
      - generic [ref=e82]:
        - generic [ref=e83]:
          - generic [ref=e84]: 系统
          - button "OpenClaw" [ref=e85] [cursor=pointer]
          - button "设置" [ref=e90] [cursor=pointer]
        - button "切换到深色模式" [ref=e96] [cursor=pointer]:
          - img [ref=e97]
    - main [ref=e103]:
      - generic [ref=e630]:
        - generic [ref=e632]:
          - generic [ref=e633]
          - generic [ref=e653]
        - tabpanel [ref=e664]:
          - generic [ref=e665]
          - generic [ref=e734]
  - region "Notifications alt+T"