import {
  archiveBrowserEnvironmentPreset,
  archiveBrowserProfile,
  browserExecuteAction,
  getChromeBridgeStatus,
  getBrowserRuntimeAuditLogs,
  launchBrowserSession,
  type BrowserEnvironmentLaunchConfig,
  type BrowserEnvironmentPresetRecord,
  type BrowserSessionLaunchResponse,
  type LaunchBrowserSessionRequest,
  type OpenChromeProfileResponse,
  launchBrowserProfileRuntimeAssist,
  openChromeProfileWindow,
  closeCdpSession,
  listBrowserEnvironmentPresets,
  listBrowserProfiles,
  getBrowserEventBuffer,
  getBrowserSessionState,
  launchBrowserRuntimeAssist,
  listCdpTargets,
  openBrowserRuntimeDebuggerWindow,
  openCdpSession,
  releaseBrowserSession,
  resumeBrowserSession,
  restoreBrowserProfile,
  restoreBrowserEnvironmentPreset,
  saveBrowserProfile,
  saveBrowserEnvironmentPreset,
  startBrowserStream,
  stopBrowserStream,
  takeOverBrowserSession,
  type BrowserProfileRecord,
  type BrowserProfileTransportKind,
  type BrowserRuntimeAuditKind,
  type BrowserRuntimeAuditRecord,
  type BrowserEvent,
  type BrowserEventBufferSnapshot,
  type ChromeBridgeStatusSnapshot,
  type BrowserControlMode,
  type BrowserSessionLifecycleState,
  type BrowserStreamMode,
  type BrowserTransportKind,
  type CdpSessionState,
  type CdpTargetInfo,
  type SaveBrowserEnvironmentPresetRequest,
  type SaveBrowserProfileRequest,
} from "@/lib/webview-api";
import {
  hasNativeTauriEventSupport,
  safeListen,
} from "@/lib/dev-bridge/safeInvoke";

export type {
  BrowserEvent,
  BrowserEventBufferSnapshot,
  ChromeBridgeStatusSnapshot,
  BrowserControlMode,
  BrowserEnvironmentLaunchConfig,
  BrowserEnvironmentPresetRecord,
  BrowserProfileRecord,
  BrowserProfileTransportKind,
  BrowserRuntimeAuditKind,
  BrowserRuntimeAuditRecord,
  BrowserSessionLaunchResponse,
  LaunchBrowserSessionRequest,
  BrowserSessionLifecycleState,
  BrowserStreamMode,
  BrowserTransportKind,
  CdpSessionState,
  CdpTargetInfo,
  OpenChromeProfileResponse,
  SaveBrowserProfileRequest,
  SaveBrowserEnvironmentPresetRequest,
};

export const browserRuntimeApi = {
  listBrowserEnvironmentPresets,
  saveBrowserEnvironmentPreset,
  archiveBrowserEnvironmentPreset,
  restoreBrowserEnvironmentPreset,
  listBrowserProfiles,
  saveBrowserProfile,
  archiveBrowserProfile,
  restoreBrowserProfile,
  launchBrowserSession,
  launchBrowserProfileRuntimeAssist,
  listCdpTargets,
  openCdpSession,
  closeCdpSession,
  startBrowserStream,
  stopBrowserStream,
  getBrowserSessionState,
  takeOverBrowserSession,
  releaseBrowserSession,
  resumeBrowserSession,
  getBrowserEventBuffer,
  getBrowserRuntimeAuditLogs,
  getChromeBridgeStatus,
  openBrowserRuntimeDebuggerWindow,
  launchBrowserRuntimeAssist,
  browserExecuteAction,
  reopenProfileWindow: (params: { profile_key: string; url: string }) =>
    openChromeProfileWindow(params),
  listenBrowserEvent: (handler: (event: { payload: BrowserEvent }) => void) =>
    safeListen<BrowserEvent>("browser-event", handler),
  supportsNativeEvents: () => hasNativeTauriEventSupport(),
};
