/**
 * 由 scripts/generate-agent-runtime-clients.mjs 自动生成，请勿手改。
 */

export const AGENT_RUNTIME_COMMANDS = {
  submitTurn: "agent_runtime_submit_turn",
  interruptTurn: "agent_runtime_interrupt_turn",
  compactSession: "agent_runtime_compact_session",
  resumeThread: "agent_runtime_resume_thread",
  replayRequest: "agent_runtime_replay_request",
  getThreadRead: "agent_runtime_get_thread_read",
  promoteQueuedTurn: "agent_runtime_promote_queued_turn",
  removeQueuedTurn: "agent_runtime_remove_queued_turn",
  respondAction: "agent_runtime_respond_action",
  createSession: "agent_runtime_create_session",
  listSessions: "agent_runtime_list_sessions",
  getSession: "agent_runtime_get_session",
  updateSession: "agent_runtime_update_session",
  deleteSession: "agent_runtime_delete_session",
  exportAnalysisHandoff: "agent_runtime_export_analysis_handoff",
  exportHandoffBundle: "agent_runtime_export_handoff_bundle",
  exportEvidencePack: "agent_runtime_export_evidence_pack",
  exportReviewDecisionTemplate: "agent_runtime_export_review_decision_template",
  saveReviewDecision: "agent_runtime_save_review_decision",
  exportReplayCase: "agent_runtime_export_replay_case",
  getToolInventory: "agent_runtime_get_tool_inventory",
  spawnSubagent: "agent_runtime_spawn_subagent",
  sendSubagentInput: "agent_runtime_send_subagent_input",
  waitSubagents: "agent_runtime_wait_subagents",
  resumeSubagent: "agent_runtime_resume_subagent",
  closeSubagent: "agent_runtime_close_subagent",
} as const;

export type AgentRuntimeCommandKey = keyof typeof AGENT_RUNTIME_COMMANDS;
export type AgentRuntimeCommandName =
  (typeof AGENT_RUNTIME_COMMANDS)[AgentRuntimeCommandKey];
export type AgentRuntimeCommandDomain = "thread" | "session" | "export" | "inventory" | "subagent";
export type AgentRuntimeCommandLifecycle = "current" | "compat" | "deprecated";
export type AgentRuntimeCommandMockStrategy = "default-mock" | "mock-priority" | "bridge-only";

export interface AgentRuntimeCommandDescriptor {
  readonly key: AgentRuntimeCommandKey;
  readonly command: AgentRuntimeCommandName;
  readonly domain: AgentRuntimeCommandDomain;
  readonly requestType: string;
  readonly responseType: string;
  readonly lifecycle: AgentRuntimeCommandLifecycle;
  readonly mockStrategy: AgentRuntimeCommandMockStrategy;
  readonly docsSection: string;
}

export const AGENT_RUNTIME_COMMAND_DESCRIPTORS = [
  {
    key: "submitTurn",
    command: AGENT_RUNTIME_COMMANDS.submitTurn,
    domain: "thread",
    requestType: "AgentRuntimeSubmitTurnRequest",
    responseType: "void",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "interruptTurn",
    command: AGENT_RUNTIME_COMMANDS.interruptTurn,
    domain: "thread",
    requestType: "AgentRuntimeInterruptTurnRequest",
    responseType: "boolean",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "compactSession",
    command: AGENT_RUNTIME_COMMANDS.compactSession,
    domain: "thread",
    requestType: "AgentRuntimeCompactSessionRequest",
    responseType: "void",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "resumeThread",
    command: AGENT_RUNTIME_COMMANDS.resumeThread,
    domain: "thread",
    requestType: "AgentRuntimeResumeThreadRequest",
    responseType: "boolean",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "replayRequest",
    command: AGENT_RUNTIME_COMMANDS.replayRequest,
    domain: "thread",
    requestType: "AgentRuntimeReplayRequestRequest",
    responseType: "AgentRuntimeReplayedActionRequiredView | null",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "getThreadRead",
    command: AGENT_RUNTIME_COMMANDS.getThreadRead,
    domain: "thread",
    requestType: "{ sessionId: string }",
    responseType: "AgentRuntimeThreadReadModel",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "promoteQueuedTurn",
    command: AGENT_RUNTIME_COMMANDS.promoteQueuedTurn,
    domain: "thread",
    requestType: "AgentRuntimePromoteQueuedTurnRequest",
    responseType: "boolean",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "removeQueuedTurn",
    command: AGENT_RUNTIME_COMMANDS.removeQueuedTurn,
    domain: "thread",
    requestType: "AgentRuntimeRemoveQueuedTurnRequest",
    responseType: "boolean",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "respondAction",
    command: AGENT_RUNTIME_COMMANDS.respondAction,
    domain: "thread",
    requestType: "AgentRuntimeRespondActionRequest",
    responseType: "void",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.thread",
  },
  {
    key: "createSession",
    command: AGENT_RUNTIME_COMMANDS.createSession,
    domain: "session",
    requestType: "{ workspaceId: string; name?: string; executionStrategy?: AsterExecutionStrategy }",
    responseType: "string",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.session",
  },
  {
    key: "listSessions",
    command: AGENT_RUNTIME_COMMANDS.listSessions,
    domain: "session",
    requestType: "void",
    responseType: "AsterSessionInfo[]",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.session",
  },
  {
    key: "getSession",
    command: AGENT_RUNTIME_COMMANDS.getSession,
    domain: "session",
    requestType: "{ sessionId: string }",
    responseType: "AsterSessionDetail",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.session",
  },
  {
    key: "updateSession",
    command: AGENT_RUNTIME_COMMANDS.updateSession,
    domain: "session",
    requestType: "AgentRuntimeUpdateSessionRequest",
    responseType: "void",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.session",
  },
  {
    key: "deleteSession",
    command: AGENT_RUNTIME_COMMANDS.deleteSession,
    domain: "session",
    requestType: "{ sessionId: string }",
    responseType: "void",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.session",
  },
  {
    key: "exportAnalysisHandoff",
    command: AGENT_RUNTIME_COMMANDS.exportAnalysisHandoff,
    domain: "export",
    requestType: "{ sessionId: string }",
    responseType: "AgentRuntimeAnalysisHandoff",
    lifecycle: "current",
    mockStrategy: "mock-priority",
    docsSection: "agent-runtime.export",
  },
  {
    key: "exportHandoffBundle",
    command: AGENT_RUNTIME_COMMANDS.exportHandoffBundle,
    domain: "export",
    requestType: "{ sessionId: string }",
    responseType: "AgentRuntimeHandoffBundle",
    lifecycle: "current",
    mockStrategy: "mock-priority",
    docsSection: "agent-runtime.export",
  },
  {
    key: "exportEvidencePack",
    command: AGENT_RUNTIME_COMMANDS.exportEvidencePack,
    domain: "export",
    requestType: "{ sessionId: string }",
    responseType: "AgentRuntimeEvidencePack",
    lifecycle: "current",
    mockStrategy: "mock-priority",
    docsSection: "agent-runtime.export",
  },
  {
    key: "exportReviewDecisionTemplate",
    command: AGENT_RUNTIME_COMMANDS.exportReviewDecisionTemplate,
    domain: "export",
    requestType: "{ sessionId: string }",
    responseType: "AgentRuntimeReviewDecisionTemplate",
    lifecycle: "current",
    mockStrategy: "mock-priority",
    docsSection: "agent-runtime.export",
  },
  {
    key: "saveReviewDecision",
    command: AGENT_RUNTIME_COMMANDS.saveReviewDecision,
    domain: "export",
    requestType: "AgentRuntimeSaveReviewDecisionRequest",
    responseType: "AgentRuntimeReviewDecisionTemplate",
    lifecycle: "current",
    mockStrategy: "mock-priority",
    docsSection: "agent-runtime.export",
  },
  {
    key: "exportReplayCase",
    command: AGENT_RUNTIME_COMMANDS.exportReplayCase,
    domain: "export",
    requestType: "{ sessionId: string }",
    responseType: "AgentRuntimeReplayCase",
    lifecycle: "current",
    mockStrategy: "mock-priority",
    docsSection: "agent-runtime.export",
  },
  {
    key: "getToolInventory",
    command: AGENT_RUNTIME_COMMANDS.getToolInventory,
    domain: "inventory",
    requestType: "AgentRuntimeToolInventoryRequest",
    responseType: "AgentRuntimeToolInventory",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.inventory",
  },
  {
    key: "spawnSubagent",
    command: AGENT_RUNTIME_COMMANDS.spawnSubagent,
    domain: "subagent",
    requestType: "AgentRuntimeSpawnSubagentRequest",
    responseType: "AgentRuntimeSpawnSubagentResponse",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.subagent",
  },
  {
    key: "sendSubagentInput",
    command: AGENT_RUNTIME_COMMANDS.sendSubagentInput,
    domain: "subagent",
    requestType: "AgentRuntimeSendSubagentInputRequest",
    responseType: "AgentRuntimeSendSubagentInputResponse",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.subagent",
  },
  {
    key: "waitSubagents",
    command: AGENT_RUNTIME_COMMANDS.waitSubagents,
    domain: "subagent",
    requestType: "AgentRuntimeWaitSubagentsRequest",
    responseType: "AgentRuntimeWaitSubagentsResponse",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.subagent",
  },
  {
    key: "resumeSubagent",
    command: AGENT_RUNTIME_COMMANDS.resumeSubagent,
    domain: "subagent",
    requestType: "AgentRuntimeResumeSubagentRequest",
    responseType: "AgentRuntimeResumeSubagentResponse",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.subagent",
  },
  {
    key: "closeSubagent",
    command: AGENT_RUNTIME_COMMANDS.closeSubagent,
    domain: "subagent",
    requestType: "AgentRuntimeCloseSubagentRequest",
    responseType: "AgentRuntimeCloseSubagentResponse",
    lifecycle: "current",
    mockStrategy: "bridge-only",
    docsSection: "agent-runtime.subagent",
  },
] as const satisfies readonly AgentRuntimeCommandDescriptor[];

export const AGENT_RUNTIME_COMMAND_NAMES = [
  AGENT_RUNTIME_COMMANDS.submitTurn,
  AGENT_RUNTIME_COMMANDS.interruptTurn,
  AGENT_RUNTIME_COMMANDS.compactSession,
  AGENT_RUNTIME_COMMANDS.resumeThread,
  AGENT_RUNTIME_COMMANDS.replayRequest,
  AGENT_RUNTIME_COMMANDS.getThreadRead,
  AGENT_RUNTIME_COMMANDS.promoteQueuedTurn,
  AGENT_RUNTIME_COMMANDS.removeQueuedTurn,
  AGENT_RUNTIME_COMMANDS.respondAction,
  AGENT_RUNTIME_COMMANDS.createSession,
  AGENT_RUNTIME_COMMANDS.listSessions,
  AGENT_RUNTIME_COMMANDS.getSession,
  AGENT_RUNTIME_COMMANDS.updateSession,
  AGENT_RUNTIME_COMMANDS.deleteSession,
  AGENT_RUNTIME_COMMANDS.exportAnalysisHandoff,
  AGENT_RUNTIME_COMMANDS.exportHandoffBundle,
  AGENT_RUNTIME_COMMANDS.exportEvidencePack,
  AGENT_RUNTIME_COMMANDS.exportReviewDecisionTemplate,
  AGENT_RUNTIME_COMMANDS.saveReviewDecision,
  AGENT_RUNTIME_COMMANDS.exportReplayCase,
  AGENT_RUNTIME_COMMANDS.getToolInventory,
  AGENT_RUNTIME_COMMANDS.spawnSubagent,
  AGENT_RUNTIME_COMMANDS.sendSubagentInput,
  AGENT_RUNTIME_COMMANDS.waitSubagents,
  AGENT_RUNTIME_COMMANDS.resumeSubagent,
  AGENT_RUNTIME_COMMANDS.closeSubagent,
] as const satisfies readonly AgentRuntimeCommandName[];

export const AGENT_RUNTIME_COMMANDS_BY_DOMAIN = {
  "thread": [
    AGENT_RUNTIME_COMMANDS.submitTurn,
    AGENT_RUNTIME_COMMANDS.interruptTurn,
    AGENT_RUNTIME_COMMANDS.compactSession,
    AGENT_RUNTIME_COMMANDS.resumeThread,
    AGENT_RUNTIME_COMMANDS.replayRequest,
    AGENT_RUNTIME_COMMANDS.getThreadRead,
    AGENT_RUNTIME_COMMANDS.promoteQueuedTurn,
    AGENT_RUNTIME_COMMANDS.removeQueuedTurn,
    AGENT_RUNTIME_COMMANDS.respondAction,
  ],
  "session": [
    AGENT_RUNTIME_COMMANDS.createSession,
    AGENT_RUNTIME_COMMANDS.listSessions,
    AGENT_RUNTIME_COMMANDS.getSession,
    AGENT_RUNTIME_COMMANDS.updateSession,
    AGENT_RUNTIME_COMMANDS.deleteSession,
  ],
  "export": [
    AGENT_RUNTIME_COMMANDS.exportAnalysisHandoff,
    AGENT_RUNTIME_COMMANDS.exportHandoffBundle,
    AGENT_RUNTIME_COMMANDS.exportEvidencePack,
    AGENT_RUNTIME_COMMANDS.exportReviewDecisionTemplate,
    AGENT_RUNTIME_COMMANDS.saveReviewDecision,
    AGENT_RUNTIME_COMMANDS.exportReplayCase,
  ],
  "inventory": [
    AGENT_RUNTIME_COMMANDS.getToolInventory,
  ],
  "subagent": [
    AGENT_RUNTIME_COMMANDS.spawnSubagent,
    AGENT_RUNTIME_COMMANDS.sendSubagentInput,
    AGENT_RUNTIME_COMMANDS.waitSubagents,
    AGENT_RUNTIME_COMMANDS.resumeSubagent,
    AGENT_RUNTIME_COMMANDS.closeSubagent,
  ],
} as const satisfies Record<
  AgentRuntimeCommandDomain,
  readonly AgentRuntimeCommandName[]
>;
